CRUD-app/project/events/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.IndexView.as_view(), name="index"),
    url(r'^create/$', views.CreateView.as_view(), name="create"),
    url(r'^(?P<event_id>\d+)/edit/$', views.EditView.as_view(), name="edit"),
    url(r'^(?P<event_id>\d+)/details/$', views.DetailView.as_view(), name="edit"),
    url(r'^(?P<event_id>\d+)/delete/$', views.DeleteView.as_view(), name="delete"),
    url(r'^(?P<event_id>\d+)/attend/$', views.AttendView.as_view(), name="attend"),
    url(r'^(?P<username>\w+)/$', views.UserPosts.as_view(), name="user_posts")
]

CRUD-app/project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', auth_views.login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^events/', include('events.urls', namespace='events'))
]

CRUD-app/project/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^signup/$', views.SignUp.as_view(), name="signup"),
    url(r'^(?P<username>\w+)/delete/$', views.DeleteUser.as_view(), name="delete"),
    url(r'^logout/$', views.LogoutView.as_view(), name="logout")
]

CRUD-app/project/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Event(models.Model):
	title = models.CharField(max_length=40)
	content = models.TextField()
	created_at = models.DateTimeField(default=timezone.now)
	date = models.DateTimeField()
	creator = models.ForeignKey(User)
	location = models.CharField(max_length=100)
	attendees = models.ManyToManyField(
		User, through='events.Attendance',
		through_fields=('event', 'attendee'),
		related_name='attendees'
		)

	def __str__(self):
		return self.title


class Attendance(models.Model):
	attendee = models.ForeignKey(User)
	event = models.ForeignKey(Event)

	def __str__(self):
		return "{}".format(self.event)

CRUD-app/project/users/models.py
from django.db import models

# Create your models here.

CRUD-app/project/events/forms.py
from django import forms
from django.forms import ModelForm

from .models import Event

class EventCreationForm(forms.ModelForm):

	class Meta:
		model = Event
		fields = ('title', 'content', 'location', 'date', 'creator')
		widgets = {
			"creator": forms.HiddenInput(),
			"date": forms.DateTimeInput(attrs=dict(type='datetime'))
		}

CRUD-app/project/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

CRUD-app/project/events/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from .forms import EventCreationForm
from .models import Event, Attendance

# Create your views here.
class IndexView(View):
	def get(self, request):
		events = Event.objects.all()
		user = request.user
		context = {
			'events': events,
			'user': user
		}
		return render(request, 'events/index.html', context)


class CreateView(LoginRequiredMixin, View):
	def get(self, request):
		form = EventCreationForm(initial={"creator": request.user})
		return render(request, "events/create.html", {"form":form})

	def post(self, request):
		form = EventCreationForm(request.POST)
		if form.is_valid():
			post = form.save()
			print("form is valid")
			return redirect('/events/index/')
		else:
			return render(request, "events/create.html", {"form":form})

class EditView(LoginRequiredMixin, View):
	def get(self, request, event_id):
		obj = get_object_or_404(Event, id=event_id, creator=request.user)
		form = EventCreationForm(instance=obj)
		context = {
			'form':form
		}

		return render(request, 'events/edit.html', context)


	def post(self, request, event_id):
		obj = get_object_or_404(Event, id=event_id, creator=request.user)

		form = EventCreationForm(request.POST, instance=obj)
		
		if form.is_valid():
			event = form.save()
			return redirect('events:index')
		
		else:
			context = {
				'form': form
			}

			return render(request, 'events/edit.html', context)

class DetailView(LoginRequiredMixin, View):
	def get(self, request, event_id):
		event = Event.objects.get(id=event_id)
		attendees = Attendance.objects.filter(event=event)
		context = {
			"event": event,
			"attendees":attendees
		}
		return render(request, 'events/details.html', context)


class DeleteView(LoginRequiredMixin, View):
	def get(self, request, event_id):
		event = Event.objects.get(id=event_id)
		current_user = request.user
		context = {
			'current_user' : current_user,
			'event' : event
		}

		if request.user != event.creator:
			return render(request, 'events/wrong_user.html', context)
		else:
			return render(request, 'events/delete.html', context)

	def post(self, request, event_id):
		event = Event.objects.get(id=event_id)
		event.delete()
		print('Event deleted!')
		return HttpResponseRedirect('/events/index')


class UserPosts(LoginRequiredMixin, View):
	def get(self, request, username):
		user = User.objects.get(username=username)
		print(user.username)
		pk = user.id
		events = Event.objects.filter(creator=pk)
		events_attending = Attendance.objects.filter(attendee=user)
		context = {
			'user':user,
			'events': events,
			'events_attending': events_attending
		}
		return render(request, "events/user_posts.html", context)


class AttendView(LoginRequiredMixin, View):
	def get(self, request, event_id):
		event = Event.objects.get(id=event_id)

		attendance = Attendance.objects.create(attendee=request.user, event=event)
		print(attendance)

		return render(request, "events/attended.html", {'event':event})

CRUD-app/project/users/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from passlib.hash import pbkdf2_sha256
from .forms import SignUpForm

class SignUp(View):
	
	def post(self, request):
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			login(request, user)
			return HttpResponseRedirect('/events/index/')
	
	def get(self, request):
		form = SignUpForm()
		return render(request, 'users/signup.html', {'form': form})


class DeleteUser(View):
	def get(self, request, username):
		user = User.objects.get(username=username)
		return render(request, 'users/delete.html', {'user':user})

	def post(self, request, username):

		user = User.objects.get(username=username)
		logout(request)
		user.delete()
		print("user deleted!")
		return HttpResponseRedirect('/events/index')

class LogoutView(View):
	def get(self, request):
		logout(request)
		return HttpResponseRedirect('/')

CRUD-app/project/events/templates/events/attended.html
<p><a href="/events/index">Back to homepage</a></p>
<p><a href="/events/{{event.id}}/details">Back to details for the event</a></p>

<h1>You've been added to a list of attendees!</h1>

CRUD-app/project/events/templates/events/create.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Create an Event!</title>
	</head>
	<div style="margin-left: 40%; margin-top: 5%">
		<body>
		<p><a href="/events/index">Back to homepage</a></p>
			<form method="post">
	    		{% csrf_token %}
	    		{{ form.as_p }}
	    		<button type="submit">Create Event</button>
	    	</form>
		</body>
	</div>
</html>

CRUD-app/project/events/templates/events/delete.html
<div style="margin-left: 40%; margin-top: 5%">
	<h1>Really delete {{event.title}} by {{event.creator}}?</h1>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" name="Delete">
	</form>

	<a href="/events/index/">No! Go back!</a>
</div>

CRUD-app/project/events/templates/events/details.html
<a href="/events/index/">Back to homepage</a>
<div style="margin-left: 40%; margin-top: 5%">
	<h1>{{event.title}}</h1>
	<h2>by: {{event.creator}}</h2>
	<h3>at: {{event.location}}</h3>
	<p>created at: {{event.created_at}} </p>
	<p>{{event.content}}</p>
	<h1>Who's all going?:</h1>
	{% for attendee in attendees %}
		<p>{{ attendee.attendee }}</p>
	{% endfor %}
	<p><a href="/events/{{event.id}}/attend/">Attend Event</a></p>
	<p><a href="/events/{{event.id}}/edit/">Edit Event</a></p>
	<p><a href="/events/{{event.id}}/delete/">Delete Event</a></p>
</div>

CRUD-app/project/events/templates/events/edit.html
<div style="margin-left: 40%; margin-top: 5%">
	{% block title %}
	    Update Event
	{% endblock title %}

	{% block header %}
	    <h1>Update Event info</h1>
	{% endblock header %}


	{% block main %}
	    <form action="{% url 'events:edit' event_id=form.instance.id %}" method="POST">
	    	{{ form.as_p }}
	    	{% csrf_token %}
	    	<input type="submit" value="Update">
	    </form>
	{% endblock main %}
</div>

CRUD-app/project/events/templates/events/index.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Lori's Event Website</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>
	<body>
		<p><a href="/events/create/">Create a New Event Here!</a></p>
		<p><a href="/users/{{user}}/delete/">Delete This User?</a></p>
		<p><a href="/users/logout/">Log Out</a></p>
		<div class="container">
			<div class="row">
			{% for event in events %}
				<div class="col-sm-3 col-md-3 col-lg-3">
					<h1><a href="/events/{{event.id}}/details">{{ event.title }}</a></h1>
					<h3>Where?: {{event.location}}</h3>
					<h4>When?: {{event.date}}</h4>
					<h5>created by: <a href="/events/{{event.creator}}/">{{event.creator}}</a></h5>
					<p>{{ event.content }}</p>
					<p>created at: {{ event.created_at }}</p>
					<p><a href="/events/{{event.id}}/delete/">Delete Event</a></p>
					<p><a href="/events/{{event.id}}/edit/">Edit Event</a></p>
				</div>
			{% endfor %}
			</div>

		</div>
	</body>
</html>

CRUD-app/project/events/templates/events/user_posts.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Lori's Event Website</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>
	<body>
		<a href="/events/index">Back to all events</a>
		<div class="container">
			<div class="row">
			<h1>Events {{user.username}} has created:</h1>
			{% for event in events %}
				<div class="col-sm-3 col-md-3 col-lg-3">
					<h1><a href="/events/{{event.id}}/details">{{ event.title }}</a></h1>
					<h4>by {{event.creator }}</h4>
					<p>{{ event.content }}</p>
					<p>created at: {{ event.created_at }}</p>
					<p><a href="/events/{{event.id}}/delete/">Delete Event</a></p>
					<p><a href="/events/{{event.id}}/edit/">Edit Event</a></p>
				</div>
			{% endfor %}
			</div>
			<div class="row">
				<h1>Events {{user.username}} is attending:</h1>
				{% for event in events_attending %}
					<div class="col-sm-3 col-md-3 col-lg-3">
						<h4><a href='/events/{{event.event.id}}/details/'>{{ event }}</a></h4>
					</div>
				{% endfor %}
			</div>
		</div>
	</body>
</html>

CRUD-app/project/events/templates/events/wrong_user.html
<h1>Can not delete</h1>
<h2>You are logged in as {{current_user}}. This post was made by {{post.author}}.</h2>
<p>In order to delete this post, you must be logged in as {{event.creator}}</p>
<a href="/events/index/">Back to homepage.</a>

CRUD-app/project/users/templates/users/delete.html
<div style="margin-left: 40%; margin-top: 5%">
	<h1>Really delete this user: {{user.username}}?</h1>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" name="Delete">
	</form>

	<a href="/events/index/">Go back</a>
</div>

CRUD-app/project/users/templates/users/login.html
<div style="margin-left: 40%; margin-top: 5%">

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <h3>Don't have an account with us?</h3>
  <p>Try <a href="/users/signup/">signing up</a>!</p>
{% endblock %}
</div>

CRUD-app/project/users/templates/users/signup.html
<div style="margin-left: 40%; margin-top: 5%; width: 20%">
  <h2>Sign up</h2>
    <form method="post">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}<br>
          {{ field }}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button type="submit">Sign up</button>
    </form>
</div>